### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by vtajzich** [mohitsoni/marathon-client#5]
When do you plan to release 0.4.2 ? It contains fixes that I need for my project.

**Comment by mohitsoni** [comment]
I just released 0.4.2. Hope it helps your project.

**Comment by vtajzich** [comment]
Thanks a lot, @mohitsoni . However It's not visible in maven central repo yet. Had you push it there?

**Comment by mohitsoni** [comment]
It takes 24 hours for artifacts to get replicated. I just checked Maven central and i saw version 0.4.2: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.mohitsoni%22%20AND%20a%3A%22marathon-client%22

—
